//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQn.TurtleUtils.Tokens {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenizerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenizerMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QQn.TurtleUtils.Tokens.TokenizerMessages", typeof(TokenizerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t use type {0} as TokenGroup because it has no public parameterless constructor 的本地化字符串。
        /// </summary>
        internal static string CantUseTypeXAsTokenGroupBecauseItHasNoPublicParameterlessConstructor {
            get {
                return ResourceManager.GetString("CantUseTypeXAsTokenGroupBecauseItHasNoPublicParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no placed arguments defined 的本地化字符串。
        /// </summary>
        internal static string NoPlacedArgumentsDefined {
            get {
                return ResourceManager.GetString("NoPlacedArgumentsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;+&apos; or &apos;-&apos; must be at the end of the argument 的本地化字符串。
        /// </summary>
        internal static string PlusMinMustBeLast {
            get {
                return ResourceManager.GetString("PlusMinMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A required argument value is missing 的本地化字符串。
        /// </summary>
        internal static string RequiredArgumentValueIsMissing {
            get {
                return ResourceManager.GetString("RequiredArgumentValueIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response file &apos;{0}&apos; not found 的本地化字符串。
        /// </summary>
        internal static string ResponseFileXNotFound {
            get {
                return ResourceManager.GetString("ResponseFileXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown argument &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnknownArgumentX {
            get {
                return ResourceManager.GetString("UnknownArgumentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value expected for argument &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ValueExpectedForArgumentX {
            get {
                return ResourceManager.GetString("ValueExpectedForArgumentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more {0} members in {1} are null 的本地化字符串。
        /// </summary>
        internal static string XInYIsNull {
            get {
                return ResourceManager.GetString("XInYIsNull", resourceCulture);
            }
        }
    }
}
